In [ ]:
from qiskit.quantum_info import Statevector

In [4]:
from qiskit import QuantumCircuit
qc = QuantumCircuit(2)

qc.h(0)
qc.z(1)
qc.cx(0, 1)

# qc.draw(output='mpl')
print(qc.draw())

u = Statevector.from_instruction(qc)
display(u.draw("latex"))



     ┌───┐     
q_0: ┤ H ├──■──
     ├───┤┌─┴─┐
q_1: ┤ Z ├┤ X ├
     └───┘└───┘


<IPython.core.display.Latex object>

In [5]:
from qiskit import QuantumCircuit
qc = QuantumCircuit(2)

qc.h(0)
qc.cx(0, 1)
qc.z(1)
qc.cx(1, 0)
qc.h(1)


# qc.draw(output='mpl')
print(qc.draw())

u = Statevector.from_instruction(qc)
display(u.draw("latex"))



     ┌───┐          ┌───┐     
q_0: ┤ H ├──■───────┤ X ├─────
     └───┘┌─┴─┐┌───┐└─┬─┘┌───┐
q_1: ─────┤ X ├┤ Z ├──■──┤ H ├
          └───┘└───┘     └───┘


<IPython.core.display.Latex object>

In [6]:
import numpy as np
from qiskit.quantum_info import Operator

# Pauli-Z matrix
Z = Operator([[1, 0],
              [0, -1]])

M = Z.data

# Hermitian: M† = M
is_hermitian = np.allclose(M.conj().T, M)

# Unitary: M†M = I
is_unitary = np.allclose(M.conj().T @ M, np.eye(M.shape[0]))

print("Hermitian:", is_hermitian)
print("Unitary:", is_unitary)

Hermitian: True
Unitary: True


In [7]:
from qiskit import QuantumCircuit
from qiskit.quantum_info import Operator
import numpy as np

qc = QuantumCircuit(1)
qc.z(0)

M = Operator(qc).data

print(M)
print("Hermitian:", np.allclose(M.conj().T, M))
print("Unitary:", np.allclose(M.conj().T @ M, np.eye(2)))

[[ 1.+0.j  0.+0.j]
 [ 0.+0.j -1.+0.j]]
Hermitian: True
Unitary: True


In [ ]:
import numpy as np

def matrix_properties(M):
    M = np.asarray(M)
    I = np.eye(M.shape[0], dtype=complex)

    return {
        "Hermitian": np.allclose(M.conj().T, M),
        "Unitary": np.allclose(M.conj().T @ M, I),
    }

# Example
from qiskit.quantum_info import Operator

# This approach works for X, Y, Z, H, S, T, CNOT, or any custom matrix or Qiskit Operator.
props = matrix_properties(Operator.from_label("S").data)
print(props)

{'Hermitian': False, 'Unitary': True}


In [ ]:
from qiskit import QuantumCircuit
qc = QuantumCircuit(2)

qc.x(0)
qc.s(1)
qc.cx(1, 0)
qc.h(0)
qc.h(1)


# qc.draw(output='mpl')
print(qc.draw())

u = Statevector.from_instruction(qc)
display(u.draw("latex"))

v = Operator(qc).data
np.set_printoptions(precision=3, suppress=True)
print(v)


import sympy as sp
from IPython.display import display, Math

U = sp.Matrix(2 * Operator(qc).data).applyfunc(sp.nsimplify)
display(Math(r"\frac{1}{2}" + sp.latex(U)))


     ┌───┐┌───┐┌───┐
q_0: ┤ X ├┤ X ├┤ H ├
     ├───┤└─┬─┘├───┤
q_1: ┤ S ├──■──┤ H ├
     └───┘     └───┘


<IPython.core.display.Latex object>

[[ 0.5+0.j   0.5+0.j   0. +0.5j  0. +0.5j]
 [-0.5+0.j   0.5+0.j   0. +0.5j  0. -0.5j]
 [ 0.5+0.j   0.5+0.j   0. -0.5j  0. -0.5j]
 [-0.5+0.j   0.5+0.j   0. -0.5j  0. +0.5j]]


<IPython.core.display.Math object>

In [ ]:
# Q5
import numpy as np
from qiskit.quantum_info import Statevector

psi = Statevector([
    np.sqrt(2)/3,
    -1/3,
    np.sqrt(2)/3,
    2/3
])

psi0 = np.array([
    1/np.sqrt(3),
    np.sqrt(2/3)
], dtype=complex)

psi1 = np.array([
    np.sqrt(2/3),
    -1/np.sqrt(3)
], dtype=complex)

print(np.vdot(psi0, psi0))
print(np.vdot(psi1, psi1))
print(np.vdot(psi0, psi1))

P0 = np.outer(psi0, psi0.conj())

PI0 = np.kron(np.eye(2), P0)

prob = np.vdot(psi.data, PI0 @ psi.data).real
print(prob)

(1+0j)
(1+0j)
(-1.3606722182672922e-17+0j)
0.6666666666666667


In [ ]:
# Q6
import numpy as np
from qiskit.quantum_info import Statevector

psi0 = Statevector([5/13, 12/13])
psi1 = Statevector([12/13, -5/13])

inner_product = np.vdot(psi0.data, psi1.data)

# Convert to SymPy matrices for display
psi0_sym = sp.Matrix(psi0.data).applyfunc(sp.nsimplify)
psi1_sym = sp.Matrix(psi1.data).applyfunc(sp.nsimplify)
inner_sym = sp.nsimplify(inner_product)

display(Math(
    r"\langle \psi_0 | \psi_1 \rangle = "
    + sp.latex(psi0_sym.T)
    + sp.latex(psi1_sym)
    + " = "
    + sp.latex(inner_sym)
))

print("Inner product =", inner_product)
print("Orthogonal?", np.isclose(inner_product, 0))

<IPython.core.display.Math object>

Inner product = (-2.6277468038465255e-18+0j)
Orthogonal? True


In [35]:
# Q9

import numpy as np

ket0 = np.array([[1], [0]])
ket1 = np.array([[0], [1]])
print(ket0 @ ket0.T)
print(ket0 @ ket1.T)
print(ket1 @ ket0.T)
print(ket1 @ ket1.T)

M = (
    2 * ket0 @ ket0.T
    - 1 * ket0 @ ket1.T
    - 9 * ket1 @ ket0.T
    + 3 * ket1 @ ket1.T
)

print(M)

[[1 0]
 [0 0]]
[[0 1]
 [0 0]]
[[0 0]
 [1 0]]
[[0 0]
 [0 1]]
[[ 2 -1]
 [-9  3]]


In [65]:

import numpy as np

ketu = np.array([[-2], [1]])
ketv = np.array([
    [1],
    [0],
    [1]
])
ketw = np.array([[4], [1]])
ketx = np.array([
    [1/2],
    [1/2],
    [1/2]
])

print(ketu, "\n\n", ketv, "\n\n", ketw, "\n\n", ketx, "\n\n")

# uv = np.kron(ketu, ketv)

# print(uv)


# Tensor products
uv = np.kron(ketu, ketv)
wx = np.kron(ketw, ketx)

# Compute |u>⊗|v> - (2/3)|w>⊗|x>
result = uv - (2/3) * wx

print(result)


[[-2]
 [ 1]] 

 [[1]
 [0]
 [1]] 

 [[4]
 [1]] 

 [[0.5]
 [0.5]
 [0.5]] 


[[-3.333]
 [-1.333]
 [-3.333]
 [ 0.667]
 [-0.333]
 [ 0.667]]
